# Centralized constants for API metadata, tags, and route prefixes.
#
from typing import Final


# API metadata
API_TITLE: Final[str] = "DrZaius API"


class Tags:
    CHATS: Final[str] = "Chats"
    USER_CHATS: Final[str] = "User Chats"
    MESSAGES: Final[str] = "Messages"
    PARTICIPANTS: Final[str] = "Participants"
    AUTH: Final[str] = "Auth"
    USERS: Final[str] = "Users"
    RECIPIENTS: Final[str] = "Recipients"
    RELATIONS: Final[str] = "Relations"
    CAREGIVERS: Final[str] = "Caregivers"
    RECIPIENT_DATA: Final[str] = "Recipient Data"
    ACCESS: Final[str] = "Access"
    SECURITY: Final[str] = "Security"
    COMPLIANCE: Final[str] = "Compliance"
    OPS: Final[str] = "Ops"
    FILES: Final[str] = "Files"


class Prefix:
    CHATS: Final[str] = "/chats"
    CHAT_MESSAGES: Final[str] = "/chats/{chatId}/messages"
    CHAT_PARTICIPANTS: Final[str] = "/chats/{chatId}/participants"
    USER_CHATS: Final[str] = "/users/{userId}/chats"
    AUTH: Final[str] = "/auth"
    USERS: Final[str] = "/users"
    RECIPIENTS: Final[str] = "/recipients"
    CAREGIVERS: Final[str] = "/caregivers"
    CAREGIVER_RECIPIENTS: Final[str] = "/caregivers/{caregiverId}/recipients"
    RECIPIENT_FILES: Final[str] = "/recipients/{id}/files"
    CAREGIVER_INVITATIONS: Final[str] = "/caregivers/{caregiverId}/invitations"
    RECIPIENT_INVITATIONS: Final[str] = "/recipients/{recipientId}/invitations"
    RECIPIENT_ACCESS: Final[str] = "/recipients/{recipientId}/caregivers"
    SECURITY_KEYS: Final[str] = "/security/keys"
    SECURITY_POLICIES: Final[str] = "/security/policies"
    COMPLIANCE: Final[str] = "/compliance"
    RECIPIENT_CAREGIVERS: Final[str] = "/recipients/{recipientId}/caregivers"
    FILES: Final[str] = "/files"


class Summaries:
    LIST_CHATS: Final[str] = "Get a list of all chats"
    GET_CHAT: Final[str] = "Get a specific chat by ID"
    CREATE_CHAT: Final[str] = "Create a new chat"
    UPDATE_CHAT: Final[str] = "Update a chat by ID"
    DELETE_CHAT: Final[str] = "Delete a chat by ID"
    CHAT_EMBEDDINGS_CREATE: Final[str] = "Generate embeddings for a chat"
    CHAT_EMBEDDINGS_GET: Final[str] = "Get embeddings for a chat"
    MESSAGE_CREATE: Final[str] = "Create message in chat"
    MESSAGE_LIST: Final[str] = "List messages in chat"
    MESSAGE_GET: Final[str] = "Get message by ID"
    MESSAGE_UPDATE: Final[str] = "Update message by ID"
    MESSAGE_DELETE: Final[str] = "Delete message by ID"
    PARTICIPANTS_LIST: Final[str] = "List participants in a chat"
    PARTICIPANTS_ADD: Final[str] = "Add participant to a chat"
    PARTICIPANTS_REMOVE: Final[str] = "Remove participant from a chat"
    SIGNUP: Final[str] = "Create a new user account"
    LOGIN: Final[str] = "Log in and receive authentication token"
    LOGOUT: Final[str] = "Log out and invalidate token"
    AUTH_ME: Final[str] = "Get current user"
    USERS_LIST: Final[str] = "Get a list of users"
    USER_CREATE: Final[str] = "Create a user (admin)"
    USER_GET: Final[str] = "Get a specific user by ID"
    USER_UPDATE: Final[str] = "Update user details"
    USER_DELETE: Final[str] = "Delete user (admin)"
    RECIPIENTS_LIST: Final[str] = "Get a list of all recipients"
    RECIPIENT_CREATE: Final[str] = "Register a new recipient (admin only)"
    RECIPIENT_GET: Final[str] = "Get a specific recipient's details"
    RECIPIENT_UPDATE: Final[str] = "Update a recipient's details"
    RECIPIENT_DELETE: Final[str] = "Delete a recipient"
    CAREGIVERS_LIST: Final[str] = "Get a list of all caregivers"
    CAREGIVER_CREATE: Final[str] = "Register a new caregiver"
    CAREGIVER_GET: Final[str] = "Get a specific caregiver's details"
    CAREGIVER_UPDATE: Final[str] = "Update a caregiver's details"
    CAREGIVER_DELETE: Final[str] = "Delete a user as caregiver"
    FILE_UPLOAD: Final[str] = "Upload a file"
    FILE_GET: Final[str] = "Get a specific file by ID"
    FILE_DELETE: Final[str] = "Delete a file by ID"
    FILE_EMBEDDINGS_CREATE: Final[str] = "Generate embeddings for a file"
    FILE_EMBEDDINGS_GET: Final[str] = "Get embeddings for a file"
    FILE_DOWNLOAD: Final[str] = "Download file by ID"
    FILE_ACCESS_LIST: Final[str] = "List file access control entries"
    FILE_ACCESS_GRANT: Final[str] = "Grant access to caregiver"
    FILE_ACCESS_UPDATE: Final[str] = "Update caregiver access level for file"
    FILE_ACCESS_REVOKE: Final[str] = "Revoke caregiver access to file"
    RECIPIENT_FILES_LIST: Final[str] = "Get a list of a recipient's files"
    RECIPIENT_CAREGIVERS_LIST: Final[str] = "Get a recipient's assigned caregivers"
    RECIPIENT_CAREGIVER_ASSIGN: Final[str] = "Assign caregiver to a recipient"
    RECIPIENT_CAREGIVER_REVOKE: Final[str] = "Recipient revokes caregiver access"
    RECIPIENT_CAREGIVER_UPDATE: Final[str] = "Update caregiver access level for recipient"
    CAREGIVER_RECIPIENTS_LIST: Final[str] = "List recipients assigned to caregiver"
    CAREGIVER_RECIPIENT_GET: Final[str] = "Get caregiver-recipient relationship details"
    INVITATIONS_SENT_LIST: Final[str] = "List invitations sent by caregiver"
    INVITATION_SEND: Final[str] = "Caregiver sends an invitation to a recipient"
    INVITATION_CANCEL: Final[str] = "Cancel a pending invitation"
    INVITATIONS_RECEIVED_LIST: Final[str] = "Get a recipient's received invitations"
    INVITATION_ACCEPT: Final[str] = "Recipient accepts a caregiver invitation"
    INVITATION_DECLINE: Final[str] = "Recipient declines a caregiver invitation"
    INVITATION_GET: Final[str] = "Get recipient invitation details"
    KEY_GENERATE: Final[str] = "Generate a new encryption key pair (admin only)"
    KEY_GET: Final[str] = "Get a specific encryption key (admin only)"
    POLICY_CREATE: Final[str] = "Create a new security policy (admin only)"
    POLICY_GET: Final[str] = "Get a specific security policy (admin only)"
    POLICY_UPDATE: Final[str] = "Update a security policy (admin only)"
    POLICY_DELETE: Final[str] = "Delete a security policy (admin only)"
    HIPAA_REPORT: Final[str] = "Generate a HIPAA compliance report"
    RISK_CREATE: Final[str] = "Initiate a new risk assessment"
    RISK_GET: Final[str] = "Get a specific risk assessment (admin only)"
    INCIDENT_CREATE: Final[str] = "Report a compliance incident or data breach"
    INCIDENT_GET: Final[str] = "Get details of a reported incident"
    HEALTHZ: Final[str] = "Liveness probe"
    READYZ: Final[str] = "Readiness probe"


class Messages:
    OK: Final[str] = "ok"
    READY: Final[str] = "ready"
    SIGNUP_SUCCESSFUL: Final[str] = "signup successful"
    ACCESS_TOKEN_FAKE: Final[str] = "fake-token"
    TOKEN_TYPE_BEARER: Final[str] = "bearer"
    CHAT_CREATED: Final[str] = "chat created"
    CHAT_UPDATED: Final[str] = "chat updated"
    MESSAGE_CREATED: Final[str] = "message created"
    MESSAGE_UPDATED: Final[str] = "message updated"
    PARTICIPANT_ADDED: Final[str] = "participant added"
    FILE_UPLOADED: Final[str] = "file uploaded"
    ACCESS_GRANTED: Final[str] = "access granted"
    ACCESS_UPDATED: Final[str] = "access updated"
    EMBEDDINGS_JOB_ENQUEUED: Final[str] = "embeddings job enqueued"
    INVITATION_SENT: Final[str] = "invitation sent"
    INVITATION_ACCEPTED: Final[str] = "invitation accepted"
    INVITATION_DECLINED: Final[str] = "invitation declined"
    USER_CREATED: Final[str] = "user created"
    USER_UPDATED: Final[str] = "user updated"
    CAREGIVER_CREATED: Final[str] = "caregiver created"
    CAREGIVER_UPDATED: Final[str] = "caregiver updated"
    RECIPIENT_CREATED: Final[str] = "recipient created"
    RECIPIENT_UPDATED: Final[str] = "recipient updated"
    POLICY_CREATED: Final[str] = "policy created"
    POLICY_UPDATED: Final[str] = "policy updated"
    KEY_PAIR_GENERATED: Final[str] = "key pair generated"
    RISK_ASSESSMENT_STARTED: Final[str] = "risk assessment started"
    INCIDENT_REPORTED: Final[str] = "incident reported"
    CAREGIVER_ASSIGNED: Final[str] = "caregiver assigned"


class Roles:
    RECIPIENT: Final[str] = "recipient"
    CAREGIVER: Final[str] = "caregiver"


class InvitationStatus:
    PENDING: Final[str] = "pending"
    ACCEPTED: Final[str] = "accepted"
    DECLINED: Final[str] = "declined"


class AccessLevel:
    READ: Final[str] = "read"
    WRITE: Final[str] = "write"
    ADMIN: Final[str] = "admin"

